import path from "path";

export const AlertLocators = {
  alertPage: "alert.xhtml",
  alertJson: path.join(process.cwd(), "test-data", "alert.json"),
  simpleAlertButton: "#j_idt88\\:j_idt91",
  simpleAlertResult: "#simple_result",
  simpleAlertConfirmButton: "#j_idt88\\:j_idt93",
  simpleAlertConfirmResult: "#result",
  sweetAlertSimpleButton: "#j_idt88\\:j_idt95",
  sweetAlertSimplePopup: "#j_idt88\\:j_idt96",
  sweetAlertSimplePopupTitle: "#j_idt88\\:j_idt96_title",
  sweetAlertSimplePopupBody: "#j_idt88\\:j_idt96_content p",
  sweetModalButton: "#j_idt88\\:j_idt100",
  sweetModalButtonPopup: "#j_idt88\\:j_idt101",
  sweetModalTitle: "#j_idt88\\:j_idt101_title",
  sweetModalBody: "#j_idt88\\:j_idt101_content p",
  closeButton: "Close",
  alertPromptDialogButton: "#j_idt88\\:j_idt104",
  alertPromptDialogConfirmButton: "#confirm_result",
  delete: "Delete",
  sweetAlertButton: "#j_idt88\\:j_idt107",
  sweetAlertTitle: "#j_idt88\\:j_idt107_title",
  confirmationButton: "Confirmation",
  sweetAlertMessage: ".ui-confirm-dialog-message",
  noText: "No",
  yesText: "Yes",
} as const;
