export const TextBoxLocators = {
  textPage: "input.xhtml",
  textBoxJson: "../test-data/textBox.json",
  typeNamePlaceHolder: "Babu Manickam",
  appendTextLocator: "#j_idt88\\:j_idt91",
  isDisabledLocator: "#j_idt88\\:j_idt93",
  clearTextLocator: "#j_idt88\\:j_idt95",
  mailIDLocator: "Your email and tab",
  aboutYouLocator: "About yourself",
  errorMessageLocator: "#j_idt106\\:thisform\\:age",
  errorMessageTextLocator: "#j_idt106\\:thisform\\:j_idt110_error-detail",
  typeNameDrop: "#j_idt106\\:auto-complete",
  dropDownClickLocator: "#j_idt106\\:auto-complete_panel",
  calendariconLocator: ".ui-button-icon-left.ui-icon.ui-icon-calendar",
  calendarPanelLocator: "#j_idt106\\:j_idt116_panel",
  currentYearLocator: ".ui-datepicker-year",
  calendarLeftArrow: ".ui-datepicker-prev.ui-corner-all",
  currentMonthLocator: ".ui-datepicker-month",
  calendarDates: "a.ui-state-default",
  fullDateInput: "#j_idt106\\:j_idt116_input",
  sliderLocator: "#j_idt106\\:slider",
  sliderValue: "55",
  sliderRangeWidth: '[class*="ui-slider-range ui-corner-all"]',
  sliderStyle: "style",
  sliderLeft: '[class*="ui-slider-handle"]',
  sliderZeroPercentage: "0%",
  oskLocator: "#j_idt106\\:j_idt122",
  oskKeyPad: "[class*=keypad-key]",
  oskKeypadClick: '[class*="keypad-special"]',
  oskInputValue: "#j_idt106\\:j_idt122",
  customToolBarEditor: ".ql-editor",
  paragraphLocator: "p",
  typeNumberToSpin: "55",
  upArrow: ".ui-icon.ui-c.ui-icon-triangle-1-n",
  typeNumberToSpinLocator: "#j_idt106\\:j_idt118_input",
  typedNumber: "aria-valuenow",
  spinningButton:
    ".ui-spinner-button.ui-spinner-up ui-corner-tr ui-button.ui-widget.ui-state-default.ui-button-text-only",
  closeButton: "Close",
  dropDownDisplayValueLocator: ".ui-autocomplete-token-label",
} as const;
